### ISSUE TITLE
newest version broke functions

### ISSUE THREAD

**Issue by vans163** [anywhichway/jsxdirect#2]
This commit broke functions https://github.com/anywhichway/jsxdirect/commit/1a2df50efb340b413b3f950ac36761e1a87db875.

Basically it makes {} stop working.  onclick={()=> alert()} is broken.

**Comment by anywhichway** [comment]
@vans163 Please try onclick="()=> alert()" and let me know if it works in your environment.

**Comment by anywhichway** [comment]
@vans163 This has been fixed.
